sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/WebexEvent.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/space/SpaceObserver.java
sdk/src/main/java/com/ciscowebex/androidsdk/space/internal/InternalSpace.java

SPARK-182446 Support to notify a space call status through SpaceObserver

SPARK-182446 Support to notify a space call status through SpaceObserver

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/CallMembership.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/CallObserver.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallMembershipImpl.java

SPARK-182443 Support to notify muted by host during a space call

SPARK-182443 Support to notify muted by host during a space call

---

sdk/src/main/java/com/ciscowebex/androidsdk/utils/http/DefaultHeadersInterceptor.java
sdk/src/main/java/com/ciscowebex/androidsdk/utils/http/HttpClient.java

[SPARK-191424](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-191424)

SPARK-191424 Not sending sensitive headers for unknown site

---

sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/MediaCapability.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/AdvancedSetting.java

[SPARK-148683](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-148683)
Please review.

SPARK-148683 Low Resolution and Frame Rate in Screen Share functionality

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/MediaCapability.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/AdvancedSetting.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Phone.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-192503](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-192503)

SPARK-192503  support for Background Noise Reduction

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/internal/crypto/KeyManager.java

[SPARK-181844](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-181844)

SPARK-181844 UNEXPECTED ERROR in messaging

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Call.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-195607](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-195607)

SPARK-195607 Setting Video Layout fully desynchronized

---

sdk/src/main/java/com/ciscowebex/androidsdk/internal/model/ParentModel.java
sdk/src/main/java/com/ciscowebex/androidsdk/message/Message.java
sdk/src/main/java/com/ciscowebex/androidsdk/message/MessageClient.java
sdk/src/main/java/com/ciscowebex/androidsdk/message/MessageObserver.java
sdk/src/main/java/com/ciscowebex/androidsdk/message/internal/InternalMessage.java
sdk/src/main/java/com/ciscowebex/androidsdk/message/internal/MessageClientImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-201536](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-201536)

SPARK-201536 Message Edit support

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java

[SPARK-191531](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-191531)

SPARK-191531 LocalLeft event incorrectly triggered

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Phone.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-189568](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-189568)

SPARK-189568 allow preview during dialling

---

sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/WmeObserver.java
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/WmeSession.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Call.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallContext.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/LocusResponse.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/MediaObserver.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/ScreenShareForegroundService.java

[SPARK-202008](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-202008)

SPARK-202008 Screenshare doesn't work if targetSDK & compileSDK version is 29

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Phone.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-200693](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-200693)

SPARK-211020 Expose service urls (from u2c and wdm) for apps to consume

---

sdk/src/main/java/com/ciscowebex/androidsdk/internal/model/LocusParticipantModel.java

[SPARK-227498](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227498)

fix same account logged in different devices bug

---

sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/com/ciscowebex/androidsdk/internal/AcquirePermissionActivity.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-200693](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-200693)

SPARK-200693 App crashes on wifi disconnect in Android 11

---

CHANGELOG.md

Change log typo fixed for 2.8.0 release

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallMembershipImpl.java

[SPARK-233365](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233365)

Same user appear twice on multi-stream mode

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/WmeSession.java

[SPARK-231211](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231211)

No Audio when testing 2.8.0

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/MediaCapability.java
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/device/AudioDeviceConnectionManager.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/Phone.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

[SPARK-219173](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219173)

SPARK-219173 With loud speaker enabled audio still comes through bluetooth headset

---

README.md

Updated the Readme.md file to correct webex.initialize code section and updated notes section to call webex.initialize before making any API calls.

ReadMe file updated for webex.initialize code and notes section

---

CHANGELOG.md
README.md

* Updated ChangeLog and ReadMe.

[3.2.1 patch]

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/internal/media/device/MediaDeviceMananger.java

* Proximity sensor video mute/unmute condition modified.
* Checking current state of local Video.
* 2.8.0.10-SNAPSHOT

Sensor - Video mute/unmute state modified.

---

sdk/build.gradle
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/CallImpl.java
sdk/src/main/java/com/ciscowebex/androidsdk/phone/internal/PhoneImpl.java

Reporting call initiated event when joining a call
Changed midSdk version to 21
2.8.0.11-SNAPSHOT

Reporting call initiated event when joining a call, changed minds version

---

CHANGELOG.md

Updated changelog for v3.9.1 release

3.9.1 Release

---

CHANGELOG.md

Release 3.14

---

CHANGELOG.md

Release 3.11.4
- updated change log

Release 3.11.4
